//==============================================================
//========================== WARNING ===========================
//==============================================================
//= Do not edit this file if you don't know what you're doing! =
//==============================================================
if (typeof checkConfigFile !== "function" || checkConfigFile() !== true) {
	document.getElementById("warn").style.display = "block";
}